### PR TITLE
[JENKINS-34525] Work around Groovy bug in Jenkins 2

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-34525](https://issues.jenkins-ci.org/browse/JENKINS-34525)

@reviewbybees esp. @daniel-beck

### CODE REVIEW

**Comment by rsandell** [comment]
:bee:

**Comment by daniel-beck** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

@JeremyMarshall or @nullin is there a maintainer for this plugin? Does not look active.

**Comment by JeremyMarshall** [comment]
I don't think my changes - to work with matrix builds ever hit production but I'm happy to take it over if @nullin doesn't want it any more

**Comment by jglick** [comment]
> I don't think my changes - to work with matrix builds ever hit production

Does not look that way.

> I'm happy to take it over if @nullin doesn't want it any more

[tips](https://wiki.jenkins-ci.org/display/JENKINS/Adopt+a+Plugin)

**Comment by JeremyMarshall** [comment]
I think what I'm saying is that the version packaged for download came from here, which doesn't have my  PR https://github.com/nullin/simple-parameterized-builds-report/releases

**Comment by jglick** [comment]
Hmm, according to https://github.com/nullin/simple-parameterized-builds-report/compare/master...jenkinsci:master vs. https://github.com/jenkinsci/simple-parameterized-builds-report-plugin/compare/master...nullin:master @nullin is cutting releases from his private fork, rather than the official @jenkinsci version, meaning that the divergent repositories need to be merged.

(@daniel-beck I wonder if we could make the update center block plugins which are not being released from the right place.)

**Comment by daniel-beck** [comment]
Yeah. Also not happy about the issue tracker. While I no longer care strongly about JIRA vs. GH, having it in the jenkinsci organization is a must in case a maintainer loses interest. Otherwise, it's a giant mess. We've just recently had to deal with that… FWIW we now ask new plugin authors to delete the repository we're forking from, so the jenkinsci one becomes the primary repo. It's worked out well so far AFAICT.

**Comment by nullin** [comment]
I'll take care of this now.

**Pull request merged**
